# Generated by Django 5.0.3 on 2024-03-12 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_section_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='section_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.section'),
        ),
    ]
