version: 2.1

jobs:
  build:
    docker:
      - image: docker:stable

    steps:
      - checkout
      - setup_remote_docker
    
      - run:
          name: Build Docker Image
          command: |
            docker build -t $IMAGE .

      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_REGION
      
      - run:
          name: Log in to AWS ECR
          command: |
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      
      - run:
          name: Tag Docker Image
          command: |
            docker tag $IMAGE:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY:latest
      
      - run:
          name: Push Docker Image to AWS ECR
          command: |
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY:latest
