version: 2.1

jobs:
  build:
    docker:
      - image: python:3.10
      
    working_directory: ~/repo
    
    steps:
      - checkout
      
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      
      - run:
          name: Collect Static Files
          command: |
            python manage.py collectstatic --no-input
      
      - run:
          name: Run Tests
          command: |
            python manage.py test
      
      - run:
          name: Build Docker Image
          command: |
            docker build -t your-image-name .
      
      - run:
          name: Log in to AWS ECR
          command: |
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      
      - run:
          name: Tag Docker Image
          command: |
            docker tag your-image-name:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/your-repo-name:latest
      
      - run:
          name: Push Docker Image to AWS ECR
          command: |
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/your-repo-name:latest

