name: Django Tests and Deploy

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Collect static files
      run: |
        python server/manage.py collectstatic --noinput

    - name: Set up environment
      run: |
        cp .env.example .env

    - name: Run tests
      run: |
        python server/manage.py test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Install lftp
      run: |
        sudo apt-get update
        sudo apt-get -y install lftp

    - name: SFTP Deploy
      run: |
        echo "${{ secrets.SFTP_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        mkdir repo_content
        cp -r !(repo_content) repo_content/
        cd repo_content
        lftp -u ${{ secrets.SFTP_USERNAME }}, -e "set sftp:auto-confirm yes; set sftp:connect-program 'ssh -i ../private_key.pem'; mirror -R . /home/ubuntu/app; quit" sftp://${{ secrets.SFTP_HOST }}
